[package]
name = "typename_derive"
version = "0.1.0"
authors = ["Motohiro <c201075@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.9"
syn = "1.0.73"

